### ISSUE TITLE
Will someone adopt and continue developing gpcp?

### ISSUE THREAD

**Issue by 3oheicrw** [k-john-gough/gpcp#19]
Could it be you, @cfbsoftware? You seem to have products using gpcp. This piece of software is awesome but it current state is very sad.

**Comment by cfbsoftware** [comment]
John Gough has consistently fixed any problems that I have reported. The .NET version currently satisfies all of my requirements. You are right - it is awesome.

**Comment by 3oheicrw** [comment]
I'm more interested in the Java version, though.

**Comment by cfbsoftware** [comment]
Sorry - I definitely can't help you there.

**Comment by k-john-gough** [comment]
Hi Chris, 3oheicrw

John here. I have not been making changes to GPCP for a couple of years. I have certainly stopped adding new features to either the compiler or the language. I have been retired from my last job (at Oracle Labs) since Jan. 2016. With both GPCP and my other open source projects (GPLEX and GPPG) I have stopped work on the sources.

Given that there are still users, particularly for the scanner and parser generation tools, I would like to keep them going. However my ability to do this is probably limited. A best case would be for someone else to take over maintaining the code, preferably someone about 60 years younger than me.

In the case of GPCP-NET this should be easy for a competent compiler guy, as I used this compiler as the running example in my 2002 book Compiling for the .NET Language Runtime. There are about 4000+ copies of this hanging around in libraries and on bookshelves. The Java version is more problematic, as there is no detailed design document. Of course there is a lot of common code between the versions.

The latest version of the Java compiler switched to using ASM as the assembler. This shields the compiler from breaking changes in the JVM format as ASM is maintained by someone other than me.

Hope this helps.

John Gough

**Comment by 3oheicrw** [comment]
The problem is, no one is interested in this language anymore. The fact is, this language has never gain tractions. Having someone voluntarily adopt it and maintaining this compiler is unrealistic. Only when you hire and paid them. The only one uses this compiler for business is @cfbsoftware so if this will be completely unmaintained in the future, maybe he could do something.
